### ISSUE TITLE
西区电信登录卡住

### ISSUE THREAD

**Issue by bunny1xd** [dafeiyoung/sguclient#12]
使用linux代码登陆后
进度卡在Drcom Got: Misc, Response for alive(or Misc,File)一行

与此同时，openwrt接口页内外网接口均已出现ip

**Comment by dafeiyoung** [comment]
关于最近电信心跳包异常: 是由于电信SGUClient已经遭到学校升级拨号器封杀，表现为SGUClient电信网用户无法上线或频繁掉线。移动网用户暂不受影响。
